import assert from 'node:assert/strict'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it } from 'node:test'

import { buildHolding } from '../portfolio'
import { groupRows, parseLankaBanglaPortfolio, parseStatementDate } from './lankabangla'
import { reconcile } from './reconcile'
import type { TextItem } from './types'

/*
 * A synthetic statement. The layout — row order, column x positions, header
 * wording — is copied from a real LankaBangla statement; every name, number
 * and identifier is invented. Real statements are never committed.
 */

/** Column x positions, as measured on a real statement. */
const X = [11, 92, 165, 213, 226, 273, 282, 339, 369, 434, 476, 532, 570]

function line(y: number, cells: [number, string][]): TextItem[] {
  return cells.map(([x, str]) => ({ x, y, str, page: 1 }))
}

function holdingRow(y: number, values: string[]): TextItem[] {
  return line(y, values.map((v, i) => [X[i], v] as [number, string]))
}

function statement(overrides: { rows?: TextItem[][]; total?: string[]; asOf?: string } = {}) {
  const rows = overrides.rows ?? [
    //          symbol  cat  sale lock lien total costPx   costAmt     mktPx     mktValue  %port   gain     %gain
    holdingRow(669, ['AAA', 'A', '10', '0', '0', '10', '100.00', '1,000.00', '110.00', '1,100.00', '53.66', '100.00', '10.00']),
    holdingRow(655, ['BBB', 'A', '3', '2', '0', '5', '200.33', '1,001.67', '190.00', '950.00', '46.34', '-51.67', '-5.16']),
  ]

  return [
    ...line(800, [[200, 'LankaBangla Securities PLC']]),
    ...line(780, [[180, 'CLIENT WISE PORTFOLIO STATEMENT']]),
    ...line(767, [[9, 'Client Code: X0001'], [132, 'Name: TEST CLIENT'], [468, 'As On:'], [497, overrides.asOf ?? '05-Jan-2026']]),
    ...line(741, [[9, 'BO ID: 1234567890123456'], [132, 'Category:CASH'], [218, 'A/C Type: Joint Holder'], [468, 'BP ID:'], [502, 'NO BPID']]),
    ...line(724, [[11, 'Company'], [95, 'Cate'], [134, 'Saleabl'], [192, 'Lock'], [218, 'Lien'], [258, 'Total'], [286, 'Cost'], [332, 'Cost'], [376, 'Market'], [424, 'Market'], [475, '%Port'], [506, 'Unrealize'], [564, '%Gai']]),
    ...line(712, [[11, 'Name'], [95, 'gory'], [159, 'e'], [198, 'Qty'], [222, 'Qty'], [261, 'Qty.'], [285, 'Price']]),
    ...line(690, [[11, 'Marginable Securities']]),
    ...rows.flat(),
    ...line(611, [[11, 'Total:'], ...(overrides.total ?? ['2,001.67', '2,050.00', '100', '48.33', '2.41']).map((v, i) => [[329, 427, 480, 531, 564][i], v] as [number, string])]),
    ...line(575, [[13, 'Cash Balance'], [143, ':'], [177, '500.25'], [356, ':'], [407, '2,050.00']]),
    // Account status: two columns of "label : value" side by side.
    ...line(565, [[236, 'Total Portfolio Value(PV)'], [358, ':'], [407, '2,050.00'], [469, 'Total'], [567, '100']]),
    ...line(544, [[13, 'Blocked for IPO/Auction'], [143, ':'], [195, '0.00'], [236, 'Equity(EQ)'], [358, ':'], [407, '2,501.92']]),
    ...line(507, [[11, 'Deposit & Withdraw Statu'], [236, 'Loan Ratio (LR)'], [356, ':'], [435, '0.00']]),
    ...line(493, [[11, 'Deposit'], [142, ':'], [167, '1,800.00']]),
    ...line(480, [[11, 'IPO/Auction Refund Reciv'], [140, ':'], [195, '40.00']]),
    ...line(467, [[11, 'Cash Dividend'], [140, ':'], [185, '25.00']]),
    ...line(454, [[11, 'Share Transfer In'], [142, ':'], [195, '0.00'], [236, 'Purchase Power (PP)'], [358, ':'], [430, '500.25']]),
    ...line(441, [[80, 'Total Deposit'], [142, ':'], [168, '1,865.00'], [236, 'Exposure on Equity'], [358, ':'], [435, '0.00']]),
    ...line(424, [[11, 'Withdraw'], [142, ':'], [195, '0.00'], [236, 'Exposure on']]),
    ...line(412, [[11, 'IPO/Auction Payment'], [140, ':'], [195, '40.00'], [236, 'Marginable'], [297, 'Equity']]),
    ...line(399, [[11, 'Share Transfer Out'], [142, ':'], [195, '0.00']]),
    ...line(387, [[74, 'Total Withdraw'], [195, '40.00']]),
    ...line(369, [[11, 'Realized Gain/Loss'], [142, ':'], [177, '120.00']]),
    ...line(284, [[11, 'Cash Dividend Receivable']]),
    ...line(262, [[9, 'SL'], [30, 'Company Name'], [179, 'Type'], [227, 'BO Holding'], [311, 'Rate'], [348, 'Cash Entitlemen'], [431, 'Record Dat'], [501, 'Deposit To']]),
    ...line(248, [[9, '1'], [30, 'Alpha Industries'], [179, 'CASH'], [257, '10.00'], [308, '5.00'], [389, '50.00'], [426, '15-Dec-2025'], [532, 'BO']]),
    ...line(17, [[11, 'Generated By:'], [536, 'Page 1 of 1']]),
  ]
}

function parse(items: TextItem[]) {
  const result = parseLankaBanglaPortfolio(items)
  if (!result.ok) throw new Error(result.reason)
  return result.statement
}

describe('parseStatementDate', () => {
  it('reads the statement format', () => {
    assert.equal(parseStatementDate('22-Sep-2026'), '2026-09-22')
    assert.equal(parseStatementDate('5-Jan-2026'), '2026-01-05')
  })

  it('refuses anything else', () => {
    for (const bad of ['2026-09-22', '22/09/2026', '32-Sep-2026', '22-Foo-2026', '']) {
      assert.equal(parseStatementDate(bad), null, bad)
    }
  })
})

describe('groupRows', () => {
  it('keeps cells that are side by side as separate cells', () => {
    // The whole reason for working from positions: flattened text fuses
    // "2,903.47" and "1,463.80" into "2,903.471,463.80".
    const rows = groupRows(line(100, [[339, '2,903.47'], [369, '1,463.80']]))
    assert.deepEqual(rows[0].cells.map((c) => c.str), ['2,903.47', '1,463.80'])
  })

  it('orders lines top of the page first', () => {
    const rows = groupRows([...line(100, [[0, 'lower']]), ...line(500, [[0, 'upper']])])
    assert.deepEqual(rows.map((r) => r.text), ['upper', 'lower'])
  })
})

describe('parseLankaBanglaPortfolio', () => {
  const s = parse(statement())

  it('reads the account header', () => {
    assert.equal(s.clientCode, 'X0001')
    assert.equal(s.boId, '1234567890123456')
    assert.equal(s.asOf, '2026-01-05')
    assert.equal(s.accountType, 'Joint Holder')
  })

  it('reads every holding, and nothing that is not one', () => {
    // "Marginable Securities" and the header's second line must not appear.
    assert.deepEqual(s.holdings.map((h) => h.symbol), ['AAA', 'BBB'])
  })

  it('reads every column correctly', () => {
    const bbb = s.holdings.find((h) => h.symbol === 'BBB')!
    assert.deepEqual(
      { ...bbb, issues: undefined },
      {
        symbol: 'BBB',
        category: 'A',
        saleableQty: 3,
        lockQty: 2,
        lienQty: 0,
        totalQty: 5,
        costPrice: 200.33,
        costAmount: 1001.67,
        marketPrice: 190,
        marketValue: 950,
        unrealised: -51.67,
        issues: undefined,
      },
    )
    assert.deepEqual(bbb.issues, [])
  })

  it('reads totals, cash, and dividends not yet paid', () => {
    assert.deepEqual(s.totals, { costAmount: 2001.67, marketValue: 2050, unrealised: 48.33 })
    assert.equal(s.cashBalance, 500.25)
    assert.deepEqual(s.dividendsReceivable, [
      { companyName: 'Alpha Industries', holding: 10, rate: 5, entitlement: 50, recordDate: '2025-12-15' },
    ])
    assert.deepEqual(s.issues, [])
  })

  it('reads the account status, each value from its own column', () => {
    assert.deepEqual(s.accountStatus, {
      marketValue: 2050,
      equity: 2501.92,
      deposit: 1800, // not "Total Deposit" on a line below
      ipoRefund: 40,
      cashDividend: 25, // not "Cash Dividend Receivable" further down
      shareTransferIn: 0,
      totalDeposit: 1865,
      withdraw: 0, // not "Total Withdraw"
      ipoPayment: 40,
      shareTransferOut: 0,
      totalWithdraw: 40,
      realisedGain: 120,
    })
  })

  it('flags account totals that do not match their own lines', () => {
    const items = statement().map((item) =>
      item.str === '1,865.00' ? { ...item, str: '9,999.00' } : item,
    )
    const bad = parse(items)
    assert.ok(bad.issues.some((i) => /Total Deposit/.test(i)))
  })

  it('flags a holding whose own arithmetic does not add up', () => {
    // A misread market value is exactly what position-based parsing guards
    // against — and exactly what the arithmetic catches if it slips through.
    const broken = parse(
      statement({
        rows: [holdingRow(669, ['AAA', 'A', '10', '0', '0', '10', '100.00', '1,000.00', '110.00', '9,999.00', '53.66', '100.00', '10.00'])],
        total: ['1,000.00', '9,999.00', '100', '100.00', '10.00'],
      }),
    )
    const aaa = broken.holdings[0]
    assert.ok(aaa.issues.some((i) => /market value/.test(i)))
    assert.ok(aaa.issues.some((i) => /unrealised/.test(i)))
  })

  it('flags quantities that do not sum', () => {
    const broken = parse(
      statement({
        rows: [holdingRow(669, ['AAA', 'A', '8', '0', '0', '10', '100.00', '1,000.00', '110.00', '1,100.00', '100', '100.00', '10.00'])],
        total: ['1,000.00', '1,100.00', '100', '100.00', '10.00'],
      }),
    )
    assert.ok(broken.holdings[0].issues.some((i) => /quantities do not add up/.test(i)))
  })

  it('reports a row it cannot read rather than guessing', () => {
    // A missing column shifts every value one place. Mapping by position
    // would silently put the market price in the cost column.
    const short = parse(
      statement({
        rows: [holdingRow(669, ['AAA', 'A', '10', '0', '0', '10', '100.00', '1,000.00', '110.00', '1,100.00', '100', '100.00'])],
        total: ['1,000.00', '1,100.00', '100', '100.00', '10.00'],
      }),
    )
    assert.equal(short.holdings.length, 0)
    assert.ok(short.issues.some((i) => /expected 13 columns/.test(i)))
  })

  it('flags a total line that disagrees with the rows', () => {
    const off = parse(statement({ total: ['9,999.00', '2,050.00', '100', '48.33', '2.41'] }))
    assert.ok(off.issues.some((i) => /cost sums to/.test(i)))
  })

  it('declines a statement from somewhere else', () => {
    const result = parseLankaBanglaPortfolio(line(700, [[0, 'Some Other Broker Ltd'], [200, 'Holdings']]))
    assert.equal(result.ok, false)
  })

  it('declines when the date is missing rather than inventing one', () => {
    const result = parseLankaBanglaPortfolio(statement({ asOf: 'unknown' }))
    assert.equal(result.ok, false)
  })
})

describe('reconcile', () => {
  const s = parse(statement())
  const AS_OF = new Date('2026-01-05T00:00:00Z')

  const ledger = (symbol: string, qty: number, price: number) =>
    buildHolding(
      symbol,
      [{ accountId: 1, symbol, tradeDate: '2025-06-01', txnType: 'buy', quantity: qty, pricePerShare: price, grossAmount: null, commission: 0, taxWithheld: 0 }],
      null,
      AS_OF,
      { id: 1, name: 'Test' },
    )

  it('proposes opening positions on a first import, pre-selected', () => {
    const suggestions = reconcile(s.holdings, [])
    assert.deepEqual(suggestions.map((x) => [x.symbol, x.kind, x.selected]), [
      ['AAA', 'opening', true],
      ['BBB', 'opening', true],
    ])
  })

  it('costs an opening position from the exact cost amount, not the rounded price', () => {
    const bbb = reconcile(s.holdings, []).find((x) => x.symbol === 'BBB')!
    // 5 x 200.33 = 1,001.65; the true cost is 1,001.67.
    assert.ok(Math.abs(bbb.proposed!.quantity * bbb.proposed!.pricePerShare - 1001.67) < 1e-9)
  })

  it('reports a match when quantities agree', () => {
    const match = reconcile(s.holdings, [ledger('AAA', 10, 100), ledger('BBB', 5, 200.334)])
    assert.deepEqual(match.map((x) => x.kind), ['match', 'match'])
    assert.ok(match.every((x) => x.proposed === null))
  })

  it('reads more shares at the same cost as a likely bonus, and does not pre-select it', () => {
    const [aaa] = reconcile([s.holdings[0]], [ledger('AAA', 8, 125)]) // 8 x 125 = 1,000
    assert.equal(aaa.kind, 'increase')
    assert.deepEqual(aaa.proposed, { txnType: 'bonus', quantity: 2, pricePerShare: 0 })
    assert.equal(aaa.selected, false)
    assert.ok(aaa.caveat)
  })

  it('reads more shares at more cost as a likely purchase', () => {
    const [aaa] = reconcile([s.holdings[0]], [ledger('AAA', 6, 100)]) // 600 cost
    assert.equal(aaa.kind, 'increase')
    assert.equal(aaa.proposed!.txnType, 'buy')
    assert.equal(aaa.proposed!.quantity, 4)
    assert.equal(aaa.proposed!.pricePerShare, 100) // (1,000 - 600) / 4
  })

  it('never proposes a sale, because the statement cannot say at what price', () => {
    // A guessed sale price would make the realised gain wrong.
    const result = reconcile([s.holdings[0]], [ledger('AAA', 15, 100), ledger('ZZZ', 3, 50)])
    const decrease = result.find((x) => x.symbol === 'AAA')!
    const exit = result.find((x) => x.symbol === 'ZZZ')!
    assert.equal(decrease.kind, 'decrease')
    assert.equal(decrease.proposed, null)
    assert.equal(exit.kind, 'exit')
    assert.equal(exit.proposed, null)
  })
})

/*
 * Against the real statements in .statements/, when there are any. That
 * folder is gitignored, so on any machine without it these are skipped.
 * They check structure only and print nothing from the statement.
 */
const STATEMENTS = join(process.cwd(), '.statements')
const realFiles = existsSync(STATEMENTS)
  ? readdirSync(STATEMENTS).filter((f) => f.toLowerCase().endsWith('.pdf'))
  : []

describe('real statements (local only)', { skip: realFiles.length === 0 }, () => {
  for (const file of realFiles) {
    it(`${file} parses cleanly, if it is a portfolio statement`, async () => {
      const { extractTextItems } = await import('./extract')
      const { detectDocument } = await import('./detect')
      const items = await extractTextItems(new Uint8Array(readFileSync(join(STATEMENTS, file))))
      if (detectDocument(items) !== 'portfolio') return
      const result = parseLankaBanglaPortfolio(items)

      assert.equal(result.ok, true, result.ok ? '' : result.reason)
      if (!result.ok) return

      const s = result.statement
      assert.match(s.boId ?? '', /^\d{16}$/)
      assert.match(s.asOf, /^\d{4}-\d{2}-\d{2}$/)
      assert.ok(s.holdings.length > 0, 'no holdings found')
      assert.ok(s.accountStatus, 'no account status section found')
      assert.ok(s.accountStatus.deposit !== null, 'no deposit figure')
      assert.ok(s.accountStatus.realisedGain !== null, 'no realised gain figure')
      // Includes the account-status totals cross-checks.
      assert.deepEqual(s.issues, [], 'statement-level issues')
      for (const h of s.holdings) assert.deepEqual(h.issues, [], `${h.symbol} failed its own arithmetic`)
    })
  }
})
